version: '2'
services:
    ablog-app:
        image: ablog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ablog-mysql:3306/ablog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ablog-mysql:
        extends:
            file: mysql.yml
            service: ablog-mysql
